# Generated by Django 4.2.27 on 2026-01-05 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(help_text='Unique case identifier', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Brief case title', max_length=500)),
                ('description', models.TextField(help_text='Detailed case description')),
                ('formation_type', models.CharField(choices=[('complaint', 'Complaint'), ('crime_scene', 'Crime Scene')], help_text='How the case was formed', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('cadet_review', 'Cadet Review'), ('officer_review', 'Officer Review'), ('rejected', 'Rejected'), ('open', 'Open'), ('under_investigation', 'Under Investigation'), ('suspects_identified', 'Suspects Identified'), ('arrest_approved', 'Arrest Approved'), ('interrogation', 'Interrogation'), ('trial_pending', 'Trial Pending'), ('closed', 'Closed')], default='draft', help_text='Current case status', max_length=30)),
                ('rejection_count', models.IntegerField(default=0, help_text='Number of times case was rejected (max 3)')),
                ('crime_scene_location', models.CharField(blank=True, help_text='Location of crime scene', max_length=500)),
                ('crime_scene_datetime', models.DateTimeField(blank=True, help_text='Date and time of crime scene discovery', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_at', models.DateTimeField(blank=True, help_text='When case was approved', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When case was closed', null=True)),
                ('assigned_cadet', models.ForeignKey(blank=True, help_text='Cadet reviewing the case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadet_cases', to=settings.AUTH_USER_MODEL)),
                ('assigned_detective', models.ForeignKey(blank=True, help_text='Detective investigating the case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detective_cases', to=settings.AUTH_USER_MODEL)),
                ('assigned_officer', models.ForeignKey(blank=True, help_text='Police officer reviewing the case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_cases', to=settings.AUTH_USER_MODEL)),
                ('assigned_sergeant', models.ForeignKey(blank=True, help_text='Sergeant overseeing the investigation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sergeant_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='User who created the case (complainant or officer)', on_delete=django.db.models.deletion.PROTECT, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrimeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Crime level name', max_length=100, unique=True)),
                ('level', models.IntegerField(choices=[(3, 'Level 3 - Minor'), (2, 'Level 2 - Medium'), (1, 'Level 1 - Major'), (0, 'Critical')], help_text='Severity level (0=Critical, 1=Major, 2=Medium, 3=Minor)', unique=True)),
                ('description', models.TextField(help_text='Description of crimes in this level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Crime Level',
                'verbose_name_plural': 'Crime Levels',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='Full name (if not registered user)', max_length=300)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=17)),
                ('national_id', models.CharField(blank=True, help_text='National ID for identification', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(help_text='Police personnel who added this witness', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_witnesses', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(help_text='Associated case', on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='cases.case')),
                ('user', models.ForeignKey(blank=True, help_text='Registered user (if witness has account)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='witnessed_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Witness',
                'verbose_name_plural': 'Witnesses',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], help_text='Review decision', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (required if rejected)')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(help_text='Case being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cases.case')),
                ('reviewer', models.ForeignKey(help_text='User conducting review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Review',
                'verbose_name_plural': 'Case Reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='crime_level',
            field=models.ForeignKey(help_text='Severity level of the crime', on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.crimelevel'),
        ),
        migrations.CreateModel(
            name='Complainant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(help_text="Complainant's statement about the incident")),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary complainant who initiated the case')),
                ('verified_by_cadet', models.BooleanField(default=False, help_text="Whether cadet verified this complainant's information")),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(help_text='Associated case', on_delete=django.db.models.deletion.CASCADE, related_name='complainants', to='cases.case')),
                ('user', models.ForeignKey(help_text='User filing complaint', on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complainant',
                'verbose_name_plural': 'Complainants',
                'ordering': ['-is_primary', '-added_at'],
                'unique_together': {('case', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_number'], name='cases_case_case_nu_a07304_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='cases_case_status_5f99d2_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['crime_level'], name='cases_case_crime_l_f27c18_idx'),
        ),
    ]
