# Generated by Django 4.2.27 on 2026-01-05 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('investigation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain_notes', models.TextField(blank=True, help_text="Captain's notes and reasoning")),
                ('chief_notes', models.TextField(blank=True, help_text="Chief's notes and reasoning (if critical case)")),
                ('trial_started_at', models.DateTimeField(auto_now_add=True)),
                ('trial_ended_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(help_text='Case being tried', on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='cases.case')),
                ('judge', models.ForeignKey(help_text='Judge presiding over trial', on_delete=django.db.models.deletion.PROTECT, related_name='presided_trials', to=settings.AUTH_USER_MODEL)),
                ('submitted_by_captain', models.ForeignKey(blank=True, help_text='Captain who submitted case to trial', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_trials_captain', to=settings.AUTH_USER_MODEL)),
                ('submitted_by_chief', models.ForeignKey(blank=True, help_text='Chief who submitted case to trial (for critical crimes)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_trials_chief', to=settings.AUTH_USER_MODEL)),
                ('suspect', models.ForeignKey(help_text='Suspect on trial', on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='investigation.suspect')),
            ],
            options={
                'verbose_name': 'Trial',
                'verbose_name_plural': 'Trials',
                'ordering': ['-trial_started_at'],
            },
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('guilty', 'Guilty'), ('innocent', 'Innocent')], help_text='Final verdict: guilty or innocent', max_length=20)),
                ('reasoning', models.TextField(help_text="Judge's detailed reasoning for verdict")),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('trial', models.OneToOneField(help_text='Trial this verdict belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='verdict', to='trial.trial')),
            ],
            options={
                'verbose_name': 'Verdict',
                'verbose_name_plural': 'Verdicts',
            },
        ),
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Brief punishment title (e.g., '5 years imprisonment')", max_length=500)),
                ('description', models.TextField(help_text='Detailed punishment description')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('verdict', models.OneToOneField(help_text='Verdict this punishment is for', on_delete=django.db.models.deletion.CASCADE, related_name='punishment', to='trial.verdict')),
            ],
            options={
                'verbose_name': 'Punishment',
                'verbose_name_plural': 'Punishments',
            },
        ),
        migrations.CreateModel(
            name='BailPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, help_text='Bail/fine amount in Rials', max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved - Awaiting Payment'), ('paid', 'Paid - Released'), ('rejected', 'Rejected')], default='pending', help_text='Payment status', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment gateway reference/transaction ID', max_length=200)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_sergeant', models.ForeignKey(blank=True, help_text='Sergeant who approved bail amount', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bail_payments', to=settings.AUTH_USER_MODEL)),
                ('suspect', models.ForeignKey(help_text='Suspect requesting bail', on_delete=django.db.models.deletion.CASCADE, related_name='bail_payments', to='investigation.suspect')),
            ],
            options={
                'verbose_name': 'Bail Payment',
                'verbose_name_plural': 'Bail Payments',
                'ordering': ['-requested_at'],
            },
        ),
    ]
