# Generated by Django 4.2.27 on 2026-01-05 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Evidence photograph', upload_to='evidence/images/')),
                ('caption', models.CharField(blank=True, help_text='Image caption/description', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title of evidence', max_length=500)),
                ('description', models.TextField(help_text='Detailed description of evidence')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When evidence was recorded')),
                ('model', models.CharField(help_text='Vehicle model', max_length=200)),
                ('color', models.CharField(help_text='Vehicle color', max_length=100)),
                ('license_plate', models.CharField(blank=True, help_text='License plate number (if available)', max_length=20)),
                ('serial_number', models.CharField(blank=True, help_text='Vehicle serial number (if no plate)', max_length=100)),
                ('case', models.ForeignKey(help_text='Associated case', on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('recorded_by', models.ForeignKey(help_text='Personnel who recorded this evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle Evidence',
                'verbose_name_plural': 'Vehicle Evidence',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title of evidence', max_length=500)),
                ('description', models.TextField(help_text='Detailed description of evidence')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When evidence was recorded')),
                ('witness_name', models.CharField(blank=True, help_text='Witness name (if not registered)', max_length=300)),
                ('transcript', models.TextField(help_text='Written transcript of testimony')),
                ('image', models.ImageField(blank=True, help_text='Image evidence from locals', null=True, upload_to='evidence/testimony/images/')),
                ('audio', models.FileField(blank=True, help_text='Audio recording', null=True, upload_to='evidence/testimony/audio/')),
                ('video', models.FileField(blank=True, help_text='Video recording', null=True, upload_to='evidence/testimony/video/')),
                ('case', models.ForeignKey(help_text='Associated case', on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('recorded_by', models.ForeignKey(help_text='Personnel who recorded this evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('witness', models.ForeignKey(blank=True, help_text='Person giving testimony (if registered user)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Testimony',
                'verbose_name_plural': 'Testimonies',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='IDDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title of evidence', max_length=500)),
                ('description', models.TextField(help_text='Detailed description of evidence')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When evidence was recorded')),
                ('owner_full_name', models.CharField(help_text='Full name on ID document', max_length=300)),
                ('document_type', models.CharField(help_text="Type of ID document (e.g., national ID, driver's license, work badge)", max_length=200)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Additional document attributes as key-value pairs (e.g., {"id_number": "123456", "issue_date": "2020-01-01"})')),
                ('case', models.ForeignKey(help_text='Associated case', on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('recorded_by', models.ForeignKey(help_text='Personnel who recorded this evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ID Document',
                'verbose_name_plural': 'ID Documents',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='GenericEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title of evidence', max_length=500)),
                ('description', models.TextField(help_text='Detailed description of evidence')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When evidence was recorded')),
                ('case', models.ForeignKey(help_text='Associated case', on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('recorded_by', models.ForeignKey(help_text='Personnel who recorded this evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generic Evidence',
                'verbose_name_plural': 'Generic Evidence',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='BiologicalEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title of evidence', max_length=500)),
                ('description', models.TextField(help_text='Detailed description of evidence')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When evidence was recorded')),
                ('evidence_type', models.CharField(help_text='Type of biological evidence (e.g., blood, hair, fingerprint)', max_length=200)),
                ('coroner_analysis', models.TextField(blank=True, help_text='Analysis results from coroner')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When evidence was verified', null=True)),
                ('case', models.ForeignKey(help_text='Associated case', on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('identity_match', models.ForeignKey(blank=True, help_text='Person matched via identity database', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_biological_evidence', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, help_text='Photos of biological evidence', related_name='biological_evidence', to='evidence.evidenceimage')),
                ('recorded_by', models.ForeignKey(help_text='Personnel who recorded this evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('verified_by_coroner', models.ForeignKey(blank=True, help_text='Coroner who verified evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_biological_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biological Evidence',
                'verbose_name_plural': 'Biological Evidence',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
