# Generated by Django 4.2.27 on 2026-01-05 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectiveBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(help_text='Case being investigated', on_delete=django.db.models.deletion.CASCADE, related_name='detective_board', to='cases.case')),
                ('detective', models.ForeignKey(help_text='Detective managing this board', on_delete=django.db.models.deletion.CASCADE, related_name='detective_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detective Board',
                'verbose_name_plural': 'Detective Boards',
            },
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('under_pursuit', 'Under Pursuit'), ('intensive_pursuit', 'Intensive Pursuit'), ('arrested', 'Arrested'), ('cleared', 'Cleared')], default='under_pursuit', help_text='Current suspect status', max_length=30)),
                ('reason', models.TextField(help_text='Why this person is suspected')),
                ('sergeant_approval_message', models.TextField(blank=True, help_text="Sergeant's approval or rejection message")),
                ('arrest_warrant_issued', models.BooleanField(default=False, help_text='Whether arrest warrant has been issued')),
                ('photo', models.ImageField(blank=True, help_text='Photo for wanted poster (if intensive pursuit)', null=True, upload_to='suspects/photos/')),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('arrested_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_sergeant', models.ForeignKey(blank=True, help_text='Sergeant who approved pursuit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_suspects', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(help_text='Case where person is suspected', on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='cases.case')),
                ('identified_by_detective', models.ForeignKey(help_text='Detective who identified this suspect', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identified_suspects', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(help_text='Person under suspicion', on_delete=django.db.models.deletion.CASCADE, related_name='suspicions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suspect',
                'verbose_name_plural': 'Suspects',
                'ordering': ['-identified_at'],
                'unique_together': {('case', 'person')},
            },
        ),
        migrations.CreateModel(
            name='TipOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(help_text='Tip information provided')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('officer_rejected', 'Rejected by Officer'), ('officer_approved', 'Approved by Officer'), ('detective_rejected', 'Rejected by Detective'), ('approved', 'Approved - Reward Available'), ('redeemed', 'Reward Redeemed')], default='pending', help_text='Current tip status', max_length=30)),
                ('redemption_code', models.CharField(blank=True, help_text='Unique code for reward redemption', max_length=20, null=True, unique=True)),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=0, help_text='Reward amount in Rials', max_digits=15, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(help_text='Case this tip is about', on_delete=django.db.models.deletion.CASCADE, related_name='tipoffs', to='cases.case')),
                ('reviewed_by_detective', models.ForeignKey(blank=True, help_text='Detective who reviewed tip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tipoffs_detective', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_officer', models.ForeignKey(blank=True, help_text='Officer who reviewed tip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tipoffs_officer', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(help_text='User who submitted tip', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tipoffs', to=settings.AUTH_USER_MODEL)),
                ('suspect', models.ForeignKey(blank=True, help_text='Suspect this tip is about (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipoffs', to='investigation.suspect')),
            ],
            options={
                'verbose_name': 'Tip-Off',
                'verbose_name_plural': 'Tip-Offs',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detective_guilt_rating', models.IntegerField(blank=True, help_text="Detective's guilt rating (1-10, 10=most guilty)", null=True)),
                ('sergeant_guilt_rating', models.IntegerField(blank=True, help_text="Sergeant's guilt rating (1-10, 10=most guilty)", null=True)),
                ('detective_notes', models.TextField(blank=True, help_text="Detective's interrogation notes")),
                ('sergeant_notes', models.TextField(blank=True, help_text="Sergeant's interrogation notes")),
                ('interrogated_at', models.DateTimeField(auto_now_add=True)),
                ('detective', models.ForeignKey(help_text='Detective conducting interrogation', on_delete=django.db.models.deletion.CASCADE, related_name='detective_interrogations', to=settings.AUTH_USER_MODEL)),
                ('sergeant', models.ForeignKey(help_text='Sergeant conducting interrogation', on_delete=django.db.models.deletion.CASCADE, related_name='sergeant_interrogations', to=settings.AUTH_USER_MODEL)),
                ('suspect', models.ForeignKey(help_text='Suspect being interrogated', on_delete=django.db.models.deletion.CASCADE, related_name='interrogations', to='investigation.suspect')),
            ],
            options={
                'verbose_name': 'Interrogation',
                'verbose_name_plural': 'Interrogations',
                'ordering': ['-interrogated_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(help_text="Type of evidence (e.g., 'testimony', 'biological', 'vehicle')", max_length=100)),
                ('object_id', models.IntegerField(help_text='ID of the evidence object')),
                ('position_x', models.FloatField(help_text='X coordinate on board (for UI positioning)')),
                ('position_y', models.FloatField(help_text='Y coordinate on board (for UI positioning)')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(help_text='Detective board containing this item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='investigation.detectiveboard')),
            ],
            options={
                'verbose_name': 'Board Item',
                'verbose_name_plural': 'Board Items',
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text="Detective's notes about this connection")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(help_text='Detective board containing this connection', on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='investigation.detectiveboard')),
                ('from_item', models.ForeignKey(help_text='Starting evidence item', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='investigation.boarditem')),
                ('to_item', models.ForeignKey(help_text='Connected evidence item', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='investigation.boarditem')),
            ],
            options={
                'verbose_name': 'Evidence Connection',
                'verbose_name_plural': 'Evidence Connections',
                'unique_together': {('board', 'from_item', 'to_item')},
            },
        ),
    ]
