# Generated by Django 4.2.27 on 2026-01-07 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasoning', models.TextField(help_text="Detective's reasoning for identifying these suspects")),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current submission status', max_length=20)),
                ('review_notes', models.TextField(blank=True, help_text="Sergeant's review notes (approval or objection)")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(help_text='Case being resolved', on_delete=django.db.models.deletion.CASCADE, related_name='suspect_submissions', to='cases.case')),
                ('detective', models.ForeignKey(help_text='Detective submitting suspects', on_delete=django.db.models.deletion.CASCADE, related_name='suspect_submissions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Sergeant who reviewed this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('suspects', models.ManyToManyField(help_text='Main suspects identified by detective', related_name='submissions', to='investigation.suspect')),
            ],
            options={
                'verbose_name': 'Suspect Submission',
                'verbose_name_plural': 'Suspect Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_evidence', 'New Evidence'), ('suspect_submission', 'Suspect Submission'), ('submission_approved', 'Submission Approved'), ('submission_rejected', 'Submission Rejected'), ('case_assigned', 'Case Assigned'), ('case_status_changed', 'Case Status Changed'), ('tipoff_submitted', 'Tip-Off Submitted'), ('reward_available', 'Reward Available'), ('general', 'General')], help_text='Type of notification', max_length=30)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message body')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of related object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(help_text='User receiving this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_case', models.ForeignKey(blank=True, help_text='Case this notification relates to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cases.case')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='investigati_recipie_5ea5f4_idx'), models.Index(fields=['recipient', 'is_read'], name='investigati_recipie_363888_idx')],
            },
        ),
    ]
