# Generated by Django 4.2.27 on 2026-01-07 13:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigation', '0002_suspectsubmission_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptainDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('guilty', 'مجرم'), ('not_guilty', 'بی\u200cگناه'), ('needs_more', 'نیاز به تحقیقات بیشتر')], help_text="Captain's final decision", max_length=20)),
                ('reasoning', models.TextField(help_text="Captain's reasoning for the decision")),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('completed', 'تکمیل شده'), ('awaiting_chief', 'در انتظار رئیس پلیس')], default='pending', help_text="Status of captain's decision", max_length=20)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('captain', models.ForeignKey(help_text='Captain making the decision', on_delete=django.db.models.deletion.CASCADE, related_name='captain_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Captain Decision',
                'verbose_name_plural': 'Captain Decisions',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.AddField(
            model_name='interrogation',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تکمیل'), ('submitted', 'ارسال شده'), ('reviewed', 'بررسی شده')], default='pending', help_text='Current status of interrogation', max_length=20),
        ),
        migrations.AddField(
            model_name='interrogation',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='detective_guilt_rating',
            field=models.IntegerField(blank=True, help_text="Detective's guilt rating (1-10, 10=most guilty)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='sergeant_guilt_rating',
            field=models.IntegerField(blank=True, help_text="Sergeant's guilt rating (1-10, 10=most guilty)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.CreateModel(
            name='PoliceChiefDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'تایید شده'), ('rejected', 'رد شده')], help_text="Police chief's decision", max_length=20)),
                ('comments', models.TextField(help_text="Police chief's comments")),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('captain_decision', models.OneToOneField(help_text='Related captain decision', on_delete=django.db.models.deletion.CASCADE, related_name='chief_decision', to='investigation.captaindecision')),
                ('police_chief', models.ForeignKey(help_text='Police chief making the decision', on_delete=django.db.models.deletion.CASCADE, related_name='chief_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Police Chief Decision',
                'verbose_name_plural': 'Police Chief Decisions',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.AddField(
            model_name='captaindecision',
            name='interrogation',
            field=models.OneToOneField(help_text='Related interrogation', on_delete=django.db.models.deletion.CASCADE, related_name='captain_decision', to='investigation.interrogation'),
        ),
    ]
