# Generated by Django 4.2.27 on 2026-01-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال بررسی'), ('completed', 'تکمیل شده')], default='pending', help_text='Trial status', max_length=20),
        ),
        migrations.AddField(
            model_name='trial',
            name='trial_date',
            field=models.DateTimeField(blank=True, help_text='Scheduled trial date', null=True),
        ),
    ]
