# Generated by Django 4.2.27 on 2026-01-07 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigation', '0003_captaindecision_interrogation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoff',
            name='detective_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for detective rejection', null=True),
        ),
        migrations.AddField(
            model_name='tipoff',
            name='detective_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipoff',
            name='officer_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for officer rejection', null=True),
        ),
        migrations.AddField(
            model_name='tipoff',
            name='officer_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipoff',
            name='redeemed_by_officer',
            field=models.ForeignKey(blank=True, help_text='Officer who processed reward redemption', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_tipoffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tipoff',
            name='reward_amount',
            field=models.DecimalField(decimal_places=0, default=5000000, help_text='Reward amount in Rials (default 5M)', max_digits=15),
        ),
    ]
