# Generated by Django 4.2.27 on 2026-02-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0004_tipoff_detective_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarditem',
            name='label',
            field=models.CharField(blank=True, default='', help_text="Display label for the board item (e.g., 'Testimony: Witness Statement')", max_length=255),
        ),
        migrations.AddField(
            model_name='boarditem',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Optional notes or description for this board item'),
        ),
    ]
